### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by leon1995** [lukevella/rallly#104]
Hello,

when I run the container I got an error that npm module could not be installed. I change the permission ownership of the directory to `1000:1000` and then I got the following error:
```
app_1  | > rallly@1.0.0 prestart /home/node
app_1  | > npm run config
app_1  | 
app_1  | 
app_1  | > rallly@1.0.0 config /home/node
app_1  | > node install.js
app_1  | 
app_1  | module.js:540
app_1  |     throw err;
app_1  |     ^
app_1  | 
app_1  | Error: Cannot find module 'prompt'
app_1  |     at Function.Module._resolveFilename (module.js:538:15)
app_1  |     at Function.Module._load (module.js:468:25)
app_1  |     at Module.require (module.js:587:17)
app_1  |     at require (internal/module.js:11:18)
app_1  |     at Object.<anonymous> (/home/node/install.js:2:14)
app_1  |     at Module._compile (module.js:643:30)
app_1  |     at Object.Module._extensions..js (module.js:654:10)
app_1  |     at Module.load (module.js:556:32)
app_1  |     at tryModuleLoad (module.js:499:12)
app_1  |     at Function.Module._load (module.js:491:3)
app_1  | npm ERR! code ELIFECYCLE
app_1  | npm ERR! errno 1
app_1  | npm ERR! rallly@1.0.0 config: `node install.js`
app_1  | npm ERR! Exit status 1
app_1  | npm ERR! 
app_1  | npm ERR! Failed at the rallly@1.0.0 config script.
app_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
app_1  | npm WARN Local package.json exists, but node_modules missing, did you mean to install?
app_1  | 
app_1  | npm ERR! A complete log of this run can be found in:
app_1  | npm ERR!     /home/node/.npm/_logs/2021-11-11T09_25_33_013Z-debug.log
app_1  | npm ERR! code ELIFECYCLE
app_1  | npm ERR! errno 1
app_1  | npm ERR! rallly@1.0.0 prestart: `npm run config`
app_1  | npm ERR! Exit status 1
app_1  | npm ERR! 
app_1  | npm ERR! Failed at the rallly@1.0.0 prestart script.
app_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
app_1  | npm WARN Local package.json exists, but node_modules missing, did you mean to install?
app_1  | 
app_1  | npm ERR! A complete log of this run can be found in:
app_1  | npm ERR!     /home/node/.npm/_logs/2021-11-11T09_25_33_030Z-debug.log
```
with `/home/node/.npm/_logs/2021-11-11T09_25_33_030Z-debug.log`:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'config' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose config Skipping project config: /home/node/.npmrc. (matches userconfig)
5 verbose run-script [ 'preconfig', 'config', 'postconfig' ]
6 info lifecycle rallly@1.0.0~preconfig: rallly@1.0.0
7 info lifecycle rallly@1.0.0~config: rallly@1.0.0
8 verbose lifecycle rallly@1.0.0~config: unsafe-perm in lifecycle true
9 verbose lifecycle rallly@1.0.0~config: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/node/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/node/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle rallly@1.0.0~config: CWD: /home/node
11 silly lifecycle rallly@1.0.0~config: Args: [ '-c', 'node install.js' ]
12 silly lifecycle rallly@1.0.0~config: Returned: code: 1  signal: null
13 info lifecycle rallly@1.0.0~config: Failed to exec config script
14 verbose stack Error: rallly@1.0.0 config: `node install.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid rallly@1.0.0
16 verbose cwd /home/node
17 verbose Linux 5.4.114-1-pve
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "config"
19 verbose node v8.9.4
20 verbose npm  v5.6.0
21 error code ELIFECYCLE
22 error errno 1
23 error rallly@1.0.0 config: `node install.js`
23 error Exit status 1
24 error Failed at the rallly@1.0.0 config script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

Can you help me, please?

**Comment by lukevella** [comment]
Sorry I wasn't able to offer support for this. There is a new release out now and I'm just refocusing my efforts on that. Closing this issue as it is no longer relevant.
