### ISSUE TITLE
The table `public.users` does not exist in the current database.

### ISSUE THREAD

**Issue by Daedalus3** [lukevella/rallly#183]
Now that #180  has been fixed (man that was fast!) the "NEXT_PUBLIC_BASE_URL" is set correctly. However I'm still running into problems when trying to create a poll or clicking the "View demo" button.

I'm getting a _"Uh oh! Something went wrong. The issue has been logged and we'll fix it as soon as possible. Please try again later."_ error message. When looking at the dev console, I'm getting a 

"http://***:**:3000/api/trpc/polls.demo.create?batch=1 500 (Internal Server Error)". 

I'm also getting a:

```
TRPCClientError: The table `public.users` does not exist in the current database.
    at Function.value (TRPCClientError-09b8a26b.esm.js:57:16)
    at s.then.f.envelope (transformRPCResponse-3700ef8b.esm.js:129:28)
    at trpc-client-links-httpBatchLink.esm.js:199:18
```

I'm not a 100% sure whether it is correct to have the parameter "DATABASE_URL" set to "postgres://postgres:postgres@rallly_db:5432/db" when using the docker image in the .env-file or if it is correct to completely remove it. Tried both options, error is the same.

Am I missing something on my end?

**Comment by lukevella** [comment]
Are you running the latest commit? There was another fix yesterday for the docker-compose file #182

**Comment by Daedalus3** [comment]
Sorry -missed that one, it fixed it. Thanks again!
