### ISSUE TITLE
500 server error on clicking "get started"

### ISSUE THREAD

**Issue by andrewzah** [lukevella/rallly#331]
**Describe the bug**
I get a 500 server error when trying to do anything.

**To Reproduce**
1. go to homepage
2. click "get started"

**Expected behavior**
Not receive a 500 server error.

**Additional context**
Rallly is being run in a docker container. [This is the dockerfile](https://github.com/andrewzah/s6-rallly/blob/3fe69a916811acf47dd6d9ce033301579b06ad99/Dockerfile).

----

```
rallly_1  | Error: iron-session: Bad usage. Minimum usage is const session = await getIronSession(req, res, { cookieName: "...", password: "...". Check the usage here: https://github.com/vvo/iron-session
rallly_1  |     at getIronSession (file:///usr/src/app/rallly/node_modules/iron-session/dist/index.mjs:19:11)
rallly_1  |     at nextGetServerSidePropsHandlerWrappedWithIronSession (/usr/src/app/rallly/.next/server/chunks/531.js:64:87)
rallly_1  |     at Object.renderToHTML (/usr/src/app/rallly/node_modules/next/dist/server/render.js:573:26)
rallly_1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
rallly_1  |     at async doRender (/usr/src/app/rallly/node_modules/next/dist/server/base-server.js:912:38)
rallly_1  |     at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (/usr/src/app/rallly/node_modules/next/dist/server/base-server.js:1017:28)
rallly_1  |     at async /usr/src/app/rallly/node_modules/next/dist/server/response-cache.js:69:36
```

**Comment by lukevella** [comment]
Hi, can you mention what commit you are running? 

Please make sure you set `SECRET_PASSWORD` in your `.env` file and make sure it's at least 3 characters

**Comment by andrewzah** [comment]
Latest commit (`10e4aaedfb5e1d8c0974ac6dbe4e1324c83f987a`), and this is my environment currently:

```
environment:
DATABASE_URL: postgres://rallly:<pw>@postgres:5432/rallly
SECRET_PASSWORD: <secret generated from openssl rand -hex 512>
SMTP_HOST: <host>
SMTP_PORT: <port>
SMTP_PWD: <token>
SMTP_SECURE: "true"
SMTP_USER: <user>
SUPPORT_EMAIL: <email>
TZ: America/New_York
 ```
