### ISSUE TITLE
rallly sending invalid smtp commands to opensmtpd

### ISSUE THREAD

**Issue by ScrumpyJack** [lukevella/Rallly#46]
```

rallly Error: Invalid login: 503 5.5.1 Invalid command: Command not supported
  rallly     at SMTPConnection._formatError (/home/me/code/rallly/node_modules/nodemailer/lib/smtp-connection/index.js:591:19)
  rallly     at SMTPConnection._actionAUTHComplete (/home/me/code/rallly/node_modules/nodemailer/lib/smtp-connection/index.js:1320:34)
  rallly     at SMTPConnection._responseActions.push.str (/home/me/code/rallly/node_modules/nodemailer/lib/smtp-connection/index.js:356:26)
  rallly     at SMTPConnection._processResponse (/home/me/code/rallly/node_modules/nodemailer/lib/smtp-connection/index.js:747:20)
  rallly     at SMTPConnection._onData (/home/me/code/rallly/node_modules/nodemailer/lib/smtp-connection/index.js:543:14)
  rallly     at Socket._socket.on.chunk (/home/me/code/rallly/node_modules/nodemailer/lib/smtp-connection/index.js:495:47)
  rallly     at emitOne (events.js:96:13)
  rallly     at Socket.emit (events.js:188:7)
  rallly     at readableAddChunk (_stream_readable.js:176:18)
  rallly     at Socket.Readable.push (_stream_readable.js:134:10)
  rallly     at TCP.onread (net.js:547:20) +30ms
```

here is the relevant log from smtp server

```
smtpd[22550]: 8a0568447a33432f smtp event=failed-command command="AUTH PLAIN AAA=" result="503 5.5.1 Invalid command: Command not supported"
smtpd[22550]: 8a0568447a33432f smtp event=closed reason=disconnect
```

here is the smtp options from my config.json

    "smtpHost": "192.168.3.1",
    "smtpPort": 25,
    "smtpUser": "",
    "smtpPwd": "",
    "smtpSecure": false

I don't require AUTH on this LAN. Would be nice to support no auth

**Comment by lukevella** [comment]
Sorry I was not able to offer support for this. Will try to address it in the new version if it still relevant.
