### ISSUE TITLE
Installation issue, Debian stretch

### ISSUE THREAD

**Issue by TwizzyDizzy** [lukevella/Rallly#53]
Hi @lukevella 

I was trying to install Rallly but could not get it up and running. First off, here's the details of my setup

Rallly version (commit hash): deed6d661a201ce7e69a0c919319d50401305ed8
Operating system: Debian Stretch (9.4)
Installation method: manual
nodejs version: 8.11.2
MongoDB version: 3.2 (as in Debian stretch)

I'm going to list all I did to be as verbose as possible:

Step 1: clone rallly, result: success
Step 2: `npm run installation`, result: success (includes entering information for `config.json`) 
Step 3: `npm start`, result: error:

``` 
sh: 1: nodemon: not found
```

Obviously `nodemon` is not listed in `package.json`, so:
Step 4: `npm install nodemon`
Step 5: `npm start`, result: error:

```
[nodemon] 1.17.5
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./bin/www`
  rallly Express server listening on port 3000 in undefined mode +0ms
  rallly connected successfully to db: mongodb://localhost:27017/rallly +19ms
  rallly Server is ready to take our messages +2s
GET / 500 194.818 ms - 1508
Error: Cannot find module 'ejs'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at new View (/opt/rallly/node_modules/express/lib/view.js:79:30)
    at Function.render (/opt/rallly/node_modules/express/lib/application.js:570:12)
    at ServerResponse.render (/opt/rallly/node_modules/express/lib/response.js:971:7)
    at /opt/rallly/config/routes.js:28:17
    at Layer.handle_error (/opt/rallly/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/opt/rallly/node_modules/express/lib/router/index.js:315:13)
    at /opt/rallly/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/rallly/node_modules/express/lib/router/index.js:335:12)
    at IncomingMessage.next (/opt/rallly/node_modules/express/lib/router/index.js:275:10)
    at done (/opt/rallly/node_modules/express/lib/response.js:966:25)
    at Object.exports.renderFile (/opt/rallly/node_modules/pug/lib/index.js:419:14)
    at View.exports.__express [as engine] (/opt/rallly/node_modules/pug/lib/index.js:464:11)
GET /favicon.ico 500 6.758 ms - 1508
Error: Cannot find module 'ejs'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at new View (/opt/rallly/node_modules/express/lib/view.js:79:30)
    at Function.render (/opt/rallly/node_modules/express/lib/application.js:570:12)
    at ServerResponse.render (/opt/rallly/node_modules/express/lib/response.js:971:7)
    at /opt/rallly/config/routes.js:28:17
    at Layer.handle_error (/opt/rallly/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/opt/rallly/node_modules/express/lib/router/index.js:315:13)
    at /opt/rallly/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/rallly/node_modules/express/lib/router/index.js:335:12)
    at IncomingMessage.next (/opt/rallly/node_modules/express/lib/router/index.js:275:10)
    at done (/opt/rallly/node_modules/express/lib/response.js:966:25)
    at Object.exports.renderFile (/opt/rallly/node_modules/pug/lib/index.js:419:14)
    at View.exports.__express [as engine] (/opt/rallly/node_modules/pug/lib/index.js:464:11)
```

Obviously `ejs` is not listed in `package.json`, so:
Step 6: `npm install ejs`

Step 7: `npm start`, result: success **BUT** upon accessing the server at the address configured in `config.json` (`siteUrl`)

``` 
[nodemon] 1.17.5
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./bin/www`
  rallly Express server listening on port 3000 in undefined mode +0ms
  rallly connected successfully to db: mongodb://localhost:27017/rallly +20ms
  rallly Server is ready to take our messages +2s
GET / 500 169.816 ms - 1669
Error: Failed to lookup view "error.ejs" in views directory "/opt/rallly/views"
    at Function.render (/opt/rallly/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/opt/rallly/node_modules/express/lib/response.js:971:7)
    at /opt/rallly/config/routes.js:28:17
    at Layer.handle_error (/opt/rallly/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/opt/rallly/node_modules/express/lib/router/index.js:315:13)
    at /opt/rallly/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/rallly/node_modules/express/lib/router/index.js:335:12)
    at IncomingMessage.next (/opt/rallly/node_modules/express/lib/router/index.js:275:10)
    at done (/opt/rallly/node_modules/express/lib/response.js:966:25)
    at Object.exports.renderFile (/opt/rallly/node_modules/pug/lib/index.js:419:14)
    at View.exports.__express [as engine] (/opt/rallly/node_modules/pug/lib/index.js:464:11)
    at View.render (/opt/rallly/node_modules/express/lib/view.js:127:8)
    at tryRender (/opt/rallly/node_modules/express/lib/application.js:640:10)
    at Function.render (/opt/rallly/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/opt/rallly/node_modules/express/lib/response.js:971:7)
    at /opt/rallly/config/routes.js:9:17
GET /favicon.ico 500 6.851 ms - 1670
Error: Failed to lookup view "error.ejs" in views directory "/opt/rallly/views"
    at Function.render (/opt/rallly/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/opt/rallly/node_modules/express/lib/response.js:971:7)
    at /opt/rallly/config/routes.js:28:17
    at Layer.handle_error (/opt/rallly/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/opt/rallly/node_modules/express/lib/router/index.js:315:13)
    at /opt/rallly/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/rallly/node_modules/express/lib/router/index.js:335:12)
    at IncomingMessage.next (/opt/rallly/node_modules/express/lib/router/index.js:275:10)
    at done (/opt/rallly/node_modules/express/lib/response.js:966:25)
    at Object.exports.renderFile (/opt/rallly/node_modules/pug/lib/index.js:419:14)
    at View.exports.__express [as engine] (/opt/rallly/node_modules/pug/lib/index.js:464:11)
    at View.render (/opt/rallly/node_modules/express/lib/view.js:127:8)
    at tryRender (/opt/rallly/node_modules/express/lib/application.js:640:10)
    at Function.render (/opt/rallly/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/opt/rallly/node_modules/express/lib/response.js:971:7)
```

From here on, I am at a loss. That's why I'm opening this issue.

Cheers & Thanks for any hint you can give
Thomas

**Comment by jbakuwel** [comment]
Same issue here. I tried going a bit further by updating config/routes.js with

    if (app.get('env') === 'developmentXX') {

Result now is:

Error: `line` is not an integer
    at Parser.initBlock (/data/www/rally.isle.nz/node_modules/pug-parser/index.js:156:36)
    at Parser.emptyBlock (/data/www/rally.isle.nz/node_modules/pug-parser/index.js:168:17)
    at Parser.block (/data/www/rally.isle.nz/node_modules/pug-parser/index.js:989:22)
    at Parser.parseBlock (/data/www/rally.isle.nz/node_modules/pug-parser/index.js:793:52)
    at Parser.parseExpr (/data/www/rally.isle.nz/node_modules/pug-parser/index.js:212:21)
    at Parser.parse (/data/www/rally.isle.nz/node_modules/pug-parser/index.js:112:25)
    at parse (/data/www/rally.isle.nz/node_modules/pug-parser/index.js:12:20)
    at Object.parse (/data/www/rally.isle.nz/node_modules/pug/lib/index.js:125:22)
    at Function.loadString [as string] (/data/www/rally.isle.nz/node_modules/pug-load/index.js:45:21)
    at compileBody (/data/www/rally.isle.nz/node_modules/pug/lib/index.js:86:18)
    at Object.exports.compile (/data/www/rally.isle.nz/node_modules/pug/lib/index.js:242:16)
    at handleTemplateCache (/data/www/rally.isle.nz/node_modules/pug/lib/index.js:215:25)
    at Object.exports.renderFile (/data/www/rally.isle.nz/node_modules/pug/lib/index.js:427:10)
    at Object.exports.renderFile (/data/www/rally.isle.nz/node_modules/pug/lib/index.js:417:21)
    at View.exports.__express [as engine] (/data/www/rally.isle.nz/node_modules/pug/lib/index.js:464:11)
    at View.render (/data/www/rally.isle.nz/node_modules/express/lib/view.js:127:8)

**Comment by tommilligan** [comment]
Hi all - not sure if they're the same issues, but I also had some errors getting set up locally and submitted PR #51 to fix them, you may find it useful. This allowed me to run Rallly locally using `docker-compose`.

@TwizzyDizzy I can tell you for sure that `mongo` 3.2 should work. However the `node` in docker-compose is only tested up to v6 LTS (boron). Try installing node 6 using [nvm](https://github.com/creationix/nvm), and see if that has any effect?

**Comment by cwesterfield** [comment]
In browser
`Error: Failed to lookup view "error.ejs" in views directory "/root/Rallly/views"
    at EventEmitter.render (/root/Rallly/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/root/Rallly/node_modules/express/lib/response.js:971:7)
    at /root/Rallly/config/routes.js:28:17
    at Layer.handle_error (/root/Rallly/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/root/Rallly/node_modules/express/lib/router/index.js:315:13)
    at /root/Rallly/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/root/Rallly/node_modules/express/lib/router/index.js:335:12)
    at IncomingMessage.next (/root/Rallly/node_modules/express/lib/router/index.js:275:10)
    at done (/root/Rallly/node_modules/express/lib/response.js:966:25)
    at Object.exports.renderFile (/root/Rallly/node_modules/pug/lib/index.js:419:14)
    at View.exports.__express [as engine] (/root/Rallly/node_modules/pug/lib/index.js:464:11)
    at View.render (/root/Rallly/node_modules/express/lib/view.js:127:8)
    at tryRender (/root/Rallly/node_modules/express/lib/application.js:640:10)
    at EventEmitter.render (/root/Rallly/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/root/Rallly/node_modules/express/lib/response.js:971:7)
    at /root/Rallly/config/routes.js:9:17`
In stretch
`GET / 500 579.773 ms - 1694
Error: Failed to lookup view "error.ejs" in views directory "/root/Rallly/views"
    at EventEmitter.render (/root/Rallly/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/root/Rallly/node_modules/express/lib/response.js:971:7)
    at /root/Rallly/config/routes.js:28:17
    at Layer.handle_error (/root/Rallly/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/root/Rallly/node_modules/express/lib/router/index.js:315:13)
    at /root/Rallly/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/root/Rallly/node_modules/express/lib/router/index.js:335:12)
    at IncomingMessage.next (/root/Rallly/node_modules/express/lib/router/index.js:275:10)
    at done (/root/Rallly/node_modules/express/lib/response.js:966:25)
    at Object.exports.renderFile (/root/Rallly/node_modules/pug/lib/index.js:419:14)
    at View.exports.__express [as engine] (/root/Rallly/node_modules/pug/lib/index.js:464:11)
    at View.render (/root/Rallly/node_modules/express/lib/view.js:127:8)
    at tryRender (/root/Rallly/node_modules/express/lib/application.js:640:10)
    at EventEmitter.render (/root/Rallly/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/root/Rallly/node_modules/express/lib/response.js:971:7)
    at /root/Rallly/config/routes.js:9:17
GET /favicon.ico 500 53.691 ms - 1695
Error: Failed to lookup view "error.ejs" in views directory "/root/Rallly/views"
    at EventEmitter.render (/root/Rallly/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/root/Rallly/node_modules/express/lib/response.js:971:7)
    at /root/Rallly/config/routes.js:28:17
    at Layer.handle_error (/root/Rallly/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/root/Rallly/node_modules/express/lib/router/index.js:315:13)
    at /root/Rallly/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/root/Rallly/node_modules/express/lib/router/index.js:335:12)
    at IncomingMessage.next (/root/Rallly/node_modules/express/lib/router/index.js:275:10)
    at done (/root/Rallly/node_modules/express/lib/response.js:966:25)
    at Object.exports.renderFile (/root/Rallly/node_modules/pug/lib/index.js:419:14)
    at View.exports.__express [as engine] (/root/Rallly/node_modules/pug/lib/index.js:464:11)
    at View.render (/root/Rallly/node_modules/express/lib/view.js:127:8)
    at tryRender (/root/Rallly/node_modules/express/lib/application.js:640:10)
    at EventEmitter.render (/root/Rallly/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/root/Rallly/node_modules/express/lib/response.js:971:7)
    at /root/Rallly/config/routes.js:22:13
`

It seems like an error.ejs file was not provided but is needed.

**Comment by TwizzyDizzy** [comment]
> @TwizzyDizzy I can tell you for sure that mongo 3.2 should work. However the node in docker-compose is only tested up to v6 LTS (boron). Try installing node 6 using nvm, and see if that has any effect?

In fact I have tested with node8 and node6. Behaviour is identical. Also the error shown (`Failed to lookup view "error.ejs"`) is just a side effect. If you create `views/error.js` with content, then this content is shown. The underlying issue, though, seems to be something different. Unfortunately the application does not write logs.

@lukevella doesn't seem to responsive either, so I guess the only reasonable thing to do here is to consider this project dead and move on. Unfortunately.

Cheers
Thomas
