### ISSUE TITLE
Deprecated function in mongoose 

### ISSUE THREAD

**Issue by danitfk** [lukevella/Rallly#58]
Hey,
First, Thanks for this such brilliant project.
There is an error when I try to deploy the project with "Docker easy way" I got this error:

```
Step 16/17 : RUN node ./bin/www
 ---> Running in af94426a525b
(node:9) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/4.x/docs/connections.html#use-mongo-client
```

Also, it will crash at this stage when use docker-compose up -d:
I must mention, I did copy sample-env to .env and put configurations.
```

> rallly@1.0.0 prestart /home/node
> npm run config


> rallly@1.0.0 config /home/node
> node install.js

module.js:540
    throw err;
    ^

Error: Cannot find module 'prompt'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/node/install.js:2:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rallly@1.0.0 config: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rallly@1.0.0 config script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

```

Docker details:
```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:08:18 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:10:42 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

Docker compose details:

```
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Comment by hidand** [comment]
I installed mongod in version 3.4 and this solved the problem.

**Comment by tommilligan** [comment]
I've already submitted PR #51 to fix the docker-compose files - please bug @lukevella if you'd like it merged.
