### ISSUE TITLE
Error sending email

### ISSUE THREAD

**Issue by YasserSpeed** [lukevella/rallly#920]
**Describe the bug**
Problem with SMTP i use zeptomail service but I try register but don't receive top I check logs and find this error

Error sending email Error: Missing credentials for "PLAIN"
    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:790:19)
    at SMTPConnection.login (/app/node_modules/nodemailer/lib/smtp-connection/index.js:444:38)
    at /app/node_modules/nodemailer/lib/smtp-transport/index.js:272:32
    at SMTPConnection.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:213:17)
    at Object.onceWrapper (node:events:631:28)
    at SMTPConnection.emit (node:events:517:28)
    at SMTPConnection.emit (node:domain:552:15)
    at SMTPConnection._actionEHLO (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1331:14)
    at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:953:20)
    at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:755:14) {
  code: 'EAUTH',
  command: 'API'
}

**Comment by lukevella** [comment]
This appears to be an issue with your configuration rather than the repo. If you find that’s not the case feel free to reopen.
