### ISSUE TITLE
OIDC Login not working with Keycloak

### ISSUE THREAD

**Issue by Tert0** [lukevella/rallly#949]
**Describe the bug**
I can not login into my Rallly Instance with Keycloak as an OIDC Provider and i get this error in the log:
```
rallly-rallly-1    | [next-auth][error][adapter_error_linkAccount] 
rallly-rallly-1    | https://next-auth.js.org/errors#adapter_error_linkaccount 
rallly-rallly-1    | Invalid `prisma.account.create()` invocation:
rallly-rallly-1    | 
rallly-rallly-1    | 
rallly-rallly-1    | {
rallly-rallly-1    |   data: {
rallly-rallly-1    |     provider: "oidc",
rallly-rallly-1    |     type: "oauth",
rallly-rallly-1    |     providerAccountId: "20.......",
rallly-rallly-1    |     access_token: "<redacted>",
rallly-rallly-1    |     expires_at: 1701275320,
rallly-rallly-1    |     refresh_expires_in: 10800,
rallly-rallly-1    |     ~~~~~~~~~~~~~~~~~~
rallly-rallly-1    |     refresh_token: "<redacted>",
rallly-rallly-1    |     token_type: "Bearer",
rallly-rallly-1    |     id_token: "<redacted>",
rallly-rallly-1    |     not-before-policy: 0,
rallly-rallly-1    |     session_state: "c.......",
rallly-rallly-1    |     scope: "openid profile email",
rallly-rallly-1    |     userId: "clp......",
rallly-rallly-1    | ?   id?: String
rallly-rallly-1    |   }
rallly-rallly-1    | }
rallly-rallly-1    | 
rallly-rallly-1    | 
rallly-rallly-1    | Unknown argument `refresh_expires_in`. Available options are listed in green. {
rallly-rallly-1    |   message: '\n' +
rallly-rallly-1    |     'Invalid `prisma.account.create()` invocation:\n' +
rallly-rallly-1    |     '\n' +
rallly-rallly-1    |     '{\n' +
rallly-rallly-1    |     '  data: {\n' +
rallly-rallly-1    |     '    provider: "oidc",\n' +
rallly-rallly-1    |     '    type: "oauth",\n' +
rallly-rallly-1    |     '    providerAccountId: "20.............",\n' +
rallly-rallly-1    |     '    access_token: "<redacted>",\n' +
rallly-rallly-1    |     '    expires_at: 1701275320,\n' +
rallly-rallly-1    |     '    refresh_expires_in: 10800,\n' +
rallly-rallly-1    |     '    ~~~~~~~~~~~~~~~~~~\n' +
rallly-rallly-1    |     '    refresh_token: "<redacted>",\n' +
rallly-rallly-1    |     '    token_type: "Bearer",\n' +
rallly-rallly-1    |     '    id_token: "<redacted>",\n' +
rallly-rallly-1    |     '    not-before-policy: 0,\n' +
rallly-rallly-1    |     '    session_state: "c.........",\n' +
rallly-rallly-1    |     '    scope: "openid profile email",\n' +
rallly-rallly-1    |     '    userId: "clp.......",\n' +
rallly-rallly-1    |     '?   id?: String\n' +
rallly-rallly-1    |     '  }\n' +
rallly-rallly-1    |     '}\n' +
rallly-rallly-1    |     '\n' +
rallly-rallly-1    |     'Unknown argument `refresh_expires_in`. Available options are listed in green.',
rallly-rallly-1    |   stack: 'PrismaClientValidationError: \n' +
rallly-rallly-1    |     'Invalid `prisma.account.create()` invocation:\n' +
rallly-rallly-1    |     '\n' +
rallly-rallly-1    |     '{\n' +
rallly-rallly-1    |     '  data: {\n' +
rallly-rallly-1    |     '    provider: "oidc",\n' +
rallly-rallly-1    |     '    type: "oauth",\n' +
rallly-rallly-1    |     '    providerAccountId: "20.......",\n' +
rallly-rallly-1    |     '    access_token: "<redacted>",\n' +
rallly-rallly-1    |     '    expires_at: 1701275320,\n' +
rallly-rallly-1    |     '    refresh_expires_in: 10800,\n' +
rallly-rallly-1    |     '    ~~~~~~~~~~~~~~~~~~\n' +
rallly-rallly-1    |     '    refresh_token: "<redacted>",\n' +
rallly-rallly-1    |     '    token_type: "Bearer",\n' +
rallly-rallly-1    |     '    id_token: "<redacted>",\n' +
rallly-rallly-1    |     '    not-before-policy: 0,\n' +
rallly-rallly-1    |     '    session_state: "c.........",\n' +
rallly-rallly-1    |     '    scope: "openid profile email",\n' +
rallly-rallly-1    |     '    userId: "clp........",\n' +
rallly-rallly-1    |     '?   id?: String\n' +
rallly-rallly-1    |     '  }\n' +
rallly-rallly-1    |     '}\n' +
rallly-rallly-1    |     '\n' +
rallly-rallly-1    |     'Unknown argument `refresh_expires_in`. Available options are listed in green.\n' +
rallly-rallly-1    |     '    at yn (/app/node_modules/@prisma/client/runtime/library.js:116:5852)\n' +
rallly-rallly-1    |     '    at wn.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:123:6429)\n' +
rallly-rallly-1    |     '    at wn.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:123:6119)\n' +
rallly-rallly-1    |     '    at wn.request (/app/node_modules/@prisma/client/runtime/library.js:123:5839)\n' +
rallly-rallly-1    |     '    at async l (/app/node_modules/@prisma/client/runtime/library.js:128:9763)',
rallly-rallly-1    |   name: 'PrismaClientValidationError'
rallly-rallly-1    | }
rallly-rallly-1    | [next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR] 
rallly-rallly-1    | https://next-auth.js.org/errors#oauth_callback_handler_error 
rallly-rallly-1    | Invalid `prisma.account.create()` invocation:
rallly-rallly-1    | 
rallly-rallly-1    | 
rallly-rallly-1    | {
rallly-rallly-1    |   data: {
rallly-rallly-1    |     provider: "oidc",
rallly-rallly-1    |     type: "oauth",
rallly-rallly-1    |     providerAccountId: "20.......................",
rallly-rallly-1    |     access_token: "<redacted>",
rallly-rallly-1    |     expires_at: 1701275320,
rallly-rallly-1    |     refresh_expires_in: 10800,
rallly-rallly-1    |     ~~~~~~~~~~~~~~~~~~
rallly-rallly-1    |     refresh_token: "<redacted>",
rallly-rallly-1    |     token_type: "Bearer",
rallly-rallly-1    |     id_token: "<redacted>",
rallly-rallly-1    |     not-before-policy: 0,
rallly-rallly-1    |     session_state: "c..........................",
rallly-rallly-1    |     scope: "openid profile email",
rallly-rallly-1    |     userId: "clp..........",
rallly-rallly-1    | ?   id?: String
rallly-rallly-1    |   }
rallly-rallly-1    | }
rallly-rallly-1    | 
rallly-rallly-1    | 
rallly-rallly-1    | Unknown argument `refresh_expires_in`. Available options are listed in green. PrismaClientValidationError: 
rallly-rallly-1    | Invalid `prisma.account.create()` invocation:
rallly-rallly-1    | 
rallly-rallly-1    | 
rallly-rallly-1    | {
rallly-rallly-1    |   data: {
rallly-rallly-1    |     provider: "oidc",
rallly-rallly-1    |     type: "oauth",
rallly-rallly-1    |     providerAccountId: "20......................",
rallly-rallly-1    |     access_token: "<redacted>",
rallly-rallly-1    |     expires_at: 1701275320,
rallly-rallly-1    |     refresh_expires_in: 10800,
rallly-rallly-1    |     ~~~~~~~~~~~~~~~~~~
rallly-rallly-1    |     refresh_token: "<redacted>",
rallly-rallly-1    |     token_type: "Bearer",
rallly-rallly-1    |     id_token: "<redacted>",
rallly-rallly-1    |     not-before-policy: 0,
rallly-rallly-1    |     session_state: "c...............................",
rallly-rallly-1    |     scope: "openid profile email",
rallly-rallly-1    |     userId: "clpj....................",
rallly-rallly-1    | ?   id?: String
rallly-rallly-1    |   }
rallly-rallly-1    | }
rallly-rallly-1    | 
rallly-rallly-1    | 
rallly-rallly-1    | Unknown argument `refresh_expires_in`. Available options are listed in green.
rallly-rallly-1    |     at yn (/app/node_modules/@prisma/client/runtime/library.js:116:5852)
rallly-rallly-1    |     at wn.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:123:6429)
rallly-rallly-1    |     at wn.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:123:6119)
rallly-rallly-1    |     at wn.request (/app/node_modules/@prisma/client/runtime/library.js:123:5839)
rallly-rallly-1    |     at async l (/app/node_modules/@prisma/client/runtime/library.js:128:9763) {
rallly-rallly-1    |   name: 'LinkAccountError',
rallly-rallly-1    |   code: undefined
rallly-rallly-1    | }

```

**To Reproduce**
1. Setup Rallly with OIDC
Set these env vars:
```env
OIDC_ENABLED=true
OIDC_DISCOVERY_URL="https://keycloak.example.com/realms/master/.well-known/openid-configuration"
OIDC_CLIENT_ID="rallly"
OIDC_CLIENT_SECRET="<redacted>"
``` 
2. Access Rallly Instance
3. Click on `Login with OpenID Connect`
4. (Login into Keycloak)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version 120

**Comment by lukevella** [comment]
Thanks for reporting. Not sure how to best handle this right now. Would appreciate help with understanding what is needed here if anyone has experience with Keycloak and next-auth.

**Comment by sir-andreas** [comment]
Not sure, whether that is valid in your case, but in my env file at least all parameters have to be entered with out quotation marks. 
eg. in your case:

```
OIDC_ENABLED=true
OIDC_DISCOVERY_URL=https://keycloak.example.com/realms/master/.well-known/openid-configuration
OIDC_CLIENT_ID=rallly
OIDC_CLIENT_SECRET=<redacted>
```

**Comment by Tert0** [comment]
> Not sure, whether that is valid in your case, but in my env file at least all parameters have to be entered with out quotation marks. eg. in your case:
> 
> ```
> OIDC_ENABLED=true
> OIDC_DISCOVERY_URL=https://keycloak.example.com/realms/master/.well-known/openid-configuration
> OIDC_CLIENT_ID=rallly
> OIDC_CLIENT_SECRET=<redacted>
> ```

Afaik env files support quotation marks and in this case  it should not make a difference, because the redirect works only the login process after the callback throws an error. I tested it without the quotation marks, but I get the same error.


> Unrelated: I've seen multiple people using the `OIDC_ENABLED` env var now. I removed this flag before releasing v3.4.0 so not sure if I've mistakenly left a reference to it somewhere in the docs. Let me know if I have.

After `v3.4.0` did not work for me (no button shown) I read through the code changes of the PR where I found that OIDC_ENABLED must be set to true, so I thought it could solve my issue, which was fixed in `v3.4.1`.

**Comment by sir-andreas** [comment]
> @sir-andreas Have you managed to get it working with Keycloak yourself?

No, I have it working with Authelia. Nevertheless in my case I had difficulties with the quotation marks. So I thought might be worth a try.

**Comment by mpldr** [comment]
Just out of curiosity, does Keycloak usually use client ids like this? Usually they are random strings like the secret, as far as I am aware.

**Comment by maximelouet** [comment]
I'm experiencing this issue as well. It seems Rallly feeds all the parameters received from the OIDC provider directly into `account.create()`, which causes issues with unknown fields.

Notably, Keycloak also adds a `not-before-policy` field in addition to the `refresh_expires_in` one, that Prisma does not understand, because it's not in the model either.

Instead of adding these fields as optional in the model, we should probably be explicitly listing only what matters to us (`access_token`, `scope`, etc) in the `account.create()` call, because we should be ignoring unknown fields in the OIDC response.

See this relevant discussion: https://lists.jboss.org/archives/list/keycloak-user@lists.jboss.org/message/VRGQE7HMYQ2YEZQM7U4X3R56QLU5UBUI/

**Comment by alexander-schoch-linuxdays** [comment]
@maximelouet I agree that we should remove only try to persist the fields defined in the prisma `Account` model. The `account.create()` call is in the PrismaAdapter from `@auth/prisma-adapter`, so we'll have to write a custom prisma adapter for this. This should not be too difficult, according to the next-auth documentation. I'll look into this in the next days.

**Comment by lukevella** [comment]
Thanks everyone for shedding some more light on this issue. I'm working on a fix (see #972) based on what's been discussed here. I've published a release candidate to test this before an official release is made. If you could try out the docker hub image `lukevella/rallly:3.5.0-rc1` and report whether this fixes the issue for you that would be very helpful.

**Comment by Tert0** [comment]
The release candidate fixed the issue for me. Thanks

**Comment by alexander-schoch-linuxdays** [comment]
@lukevella Just tested it, and it works. Thanks!

**Comment by maximelouet** [comment]
`3.5.0-rc1` fixed it for me as well, thank you!

**Comment by lukevella** [comment]
Thanks everyone for testing it out. `3.5.0` is now available 🚀
